# Generated by Django 4.2.13 on 2024-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
